name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        name: app-jar
        path: build/libs
    
    - name: Copy JAR file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "build/libs/*.jar"
        target: "~/app/"
        strip_components: 2
        timeout: 60s
    
    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        timeout: 60s
        script: |
          sudo systemctl restart todo-app